"""empty message

Revision ID: 1f9af406b29c
Revises: 41fd9cfcb076
Create Date: 2023-08-02 15:38:39.692526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9af406b29c'
down_revision = '41fd9cfcb076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('visits_sport_event_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sport_event', ['sport_event_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('visits_sport_event_id_fkey', 'sport_event', ['sport_event_id'], ['id'])

    # ### end Alembic commands ###
