"""empty message

Revision ID: 7671d536ac0d
Revises: 51a3e9b97e54
Create Date: 2023-08-01 13:57:21.730840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7671d536ac0d'
down_revision = '51a3e9b97e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
