"""empty message

Revision ID: 9f1d6e12e66d
Revises: fc6dd0c74dc6
Create Date: 2023-07-28 13:19:28.180090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1d6e12e66d'
down_revision = 'fc6dd0c74dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sport Event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.drop_column('Location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sport Event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Location', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
